apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: dex-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway

  jwtRules:
    - issuer: "http://localhost:8080/dex" # matches the `iss` in your tokens
      jwksUri: "http://dex.auth.svc.cluster.local:5556/dex/keys" # must be reachable from the gateway
      forwardOriginalToken: true
      fromHeaders:
        - name: Authorization
          prefix: "Bearer "
      outputClaimToHeaders:
        - header: kubeflow-userid
          claim: email
        - header: kubeflow-groups
          claim: groups
